### ISSUE TITLE
my computer cannot connect to the internet

### ISSUE THREAD

**Issue by miaomiao1992** [mdrokz/auto_generate_cdp#10]
because of some reason，my computer  cannot connect to the internet，so how can i call the init function avoiding panic?

**Comment by mdrokz** [comment]
> because of some reason，my computer cannot connect to the internet，so how can i call the init function avoiding of panic?

this crate relies on downloading the json protocol files from chrome devtools otherwise it wont work.

**Comment by Strum355** [comment]
Please provide a way to compile this without requiring internet access to gists. In some scenarios such as in build sandboxes where there is no internet access allowed (think nix or bazel), this crate will fail to compile without patching it to use a locally downloaded version of the protocol.
See here for an example of the issue actually happening to people: https://twitter.com/fasterthanlime/status/1709002536999436610

**Comment by mdrokz** [comment]
> Please provide a way to compile this without requiring internet access to gists. In some scenarios such as in build sandboxes where there is no internet access allowed (think nix or bazel), this crate will fail to compile without patching it to use a locally downloaded version of the protocol. See here for an example of the issue actually happening to people: https://twitter.com/fasterthanlime/status/1709002536999436610

I should have done it from the start since docs.rs is also sandboxed i have pushed a new version of auto_generate_cdp with the offline feature flag can you test it ? i have tested it from my side havent integrated it into rust_headless_chrome yet.
