### ISSUE TITLE
Build breaks on Windows

### ISSUE THREAD

**Issue by CrendKing** [mdrokz/auto_generate_cdp#12]
[This commit](https://github.com/mdrokz/auto_generate_cdp/commit/19f7df7d89133fc295ab55a836c1ac52673ab0e1) generates a `path.rs` during build, which contains the one line of `pub const MANIFEST_DIR: &str = `. Unfortunately, this doesn't work on Windows, as Cargo on Windows uses backslash as directory separator, which itself is served as escape character for Rust string. So it could look like
```
pub const MANIFEST_DIR: &str = "D:\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\auto_generate_cdp-0.4.3";
```
The error:
```
error: unknown character escape: `r`
 --> D:\Rust\debug\build\auto_generate_cdp-28e7a632cccf577f\out/path.rs:1:36
  |
1 | pub const MANIFEST_DIR: &str = "D:\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\auto_generate_cdp-0.4.3";
  |                                    ^ unknown character escape
  |
  = help: for more information, visit <https://doc.rust-lang.org/reference/tokens.html#literals>
```
I suggest either use `r` prefix for that string, or convert backslash to forward slash before outputting.

**Comment by kwinz** [comment]
I just ran into this crate breaking on Windows because it is a build dependency for [rust-headless-chrome](https://github.com/rust-headless-chrome/rust-headless-chrome/tree/main). I would appreciate if the fix pull request was merged!
